name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: kirandevtn
          password: Yadav@0107#

      - name: Build and Push Docker Image
        run: |
          docker build -t kirandevtn/wavy:${{ github.sha }} .
          docker push kirandevtn/wavy:${{ github.sha }}
